export const KNOWN_PERMISSIONS=["filesystem:read","filesystem:write","network","shell","git:write","secrets:read","browser"];
const POLICY={minimumScore:70,requiredSections:["Purpose","Instructions","Safety"],regression:{maxScoreDrop:5,failOnNewErrors:true,failOnPermissionExpansion:true}};
const RULES=[
["permission.shell","Shell execution detected",/(?:child_process|execSync\s*\(|spawnSync\s*\(|\b(?:bash|sh|zsh|powershell)\s+-c\b|```(?:bash|sh|shell)|\bsudo\s+)/gi,"shell","The skill appears capable of executing shell commands."],
["permission.network","Network access detected",/(?:\bfetch\s*\(|\baxios\b|\bcurl\s+https?:\/\/|\bwget\s+https?:\/\/)/gi,"network","The skill appears capable of making network requests."],
["permission.secrets","Secret access detected",/(?:process\.env|\.env(?:\.|\b)|\b(?:API_KEY|ACCESS_TOKEN|SECRET_KEY|PRIVATE_KEY)\b)/gi,"secrets:read","The skill references environment variables or secret material."],
["permission.git-write","Git write operation detected",/\bgit\s+(?:commit|push|tag|merge|rebase|reset\s+--hard|checkout\s+-B)\b/gi,"git:write","The skill can modify Git history or publish repository changes."],
["permission.filesystem-write","Filesystem write detected",/(?:writeFile(?:Sync)?\s*\(|appendFile(?:Sync)?\s*\(|\b(?:cat|printf|echo)\b[^\n]*>\s*[^&]|\btee\s+[^\n]+)/gi,"filesystem:write","The skill appears capable of writing files."],
["security.destructive-command","Destructive command detected",/(?:\brm\s+-rf\b|\bmkfs(?:\.|\s)|\bDROP\s+(?:TABLE|DATABASE)\b|\bDELETE\s+FROM\b|\bgit\s+reset\s+--hard\b)/gi,null,"The skill contains a potentially destructive operation that requires explicit safeguards."],
["security.approval-bypass","Human approval bypass detected",/(?:without (?:asking|confirmation|approval)|do not ask (?:the )?user|skip (?:human )?approval|auto-?approve|never request confirmation)/gi,null,"The instructions appear to bypass a human approval boundary."]];
const scalar=v=>{v=v.trim().replace(/^['"]|['"]$/g,"");if(v==="true")return true;if(v==="false")return false;if(v==="null")return null;if(/^-?\d+(?:\.\d+)?$/.test(v))return Number(v);return v};
export function parseSimpleYaml(raw){const out={};let list=null;for(const source of raw.split(/\r?\n/)){const line=source.replace(/\s+#.*$/,"");if(!line.trim())continue;const item=line.match(/^\s*-\s+(.+)$/);if(item&&list){out[list].push(scalar(item[1]));continue}const pair=line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);if(!pair)continue;const [,key,rest]=pair;const value=rest.trim();list=null;if(!value){out[key]=[];list=key}else if(value.startsWith("[")&&value.endsWith("]")){const inner=value.slice(1,-1).trim();out[key]=inner?inner.split(",").map(scalar):[]}else out[key]=scalar(value)}return out}
export function parseSkill(raw){const normalized=String(raw||"").replace(/^\uFEFF/,"");const match=normalized.match(/^---\s*\n([\s\S]*?)\n---\s*(?:\n|$)([\s\S]*)$/);return match?{raw:normalized,body:match[2].trim(),frontmatterRaw:match[1],frontmatter:parseSimpleYaml(match[1])}:{raw:normalized,body:normalized,frontmatterRaw:"",frontmatter:{}}}
const lineAt=(raw,index)=>raw.slice(0,index).split("\n").length;
const push=(list,v)=>list.push({severity:"error",...v});
function validate(skill,policy,findings){const f=skill.frontmatter;if(!skill.frontmatterRaw)push(findings,{id:"schema.frontmatter-missing",title:"YAML frontmatter is missing",message:"SKILL.md must start with YAML frontmatter delimited by --- lines.",category:"schema",line:1});for(const key of ["name","description","version","permissions"]){if(f[key]===undefined||f[key]===null||f[key]==="")push(findings,{id:`schema.required.${key}`,title:`Missing required field: ${key}`,message:`Add ${key} to the SKILL.md frontmatter.`,category:"schema",line:1})}if(f.name&&!/^[a-z0-9][a-z0-9-]{1,62}$/.test(String(f.name)))push(findings,{id:"schema.name-format",title:"Invalid skill name",message:"Use lowercase letters, numbers, and hyphens.",category:"schema",line:2,evidence:String(f.name)});if(f.version&&!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(String(f.version)))push(findings,{id:"schema.version-format",title:"Invalid semantic version",message:"Use semantic versioning such as 1.0.0.",category:"schema",line:1,evidence:String(f.version)});if(f.permissions!==undefined&&!Array.isArray(f.permissions))push(findings,{id:"schema.permissions-type",title:"Permissions must be a list",message:"Use permissions: [filesystem:read].",category:"schema",line:1});const permissions=Array.isArray(f.permissions)?f.permissions.map(String):[];for(const p of permissions)if(!KNOWN_PERMISSIONS.includes(p))push(findings,{id:"schema.permission-unknown",severity:"warning",title:"Unknown permission",message:`'${p}' is not in SkillCheck's built-in permission vocabulary.`,category:"schema",evidence:p});for(const section of policy.requiredSections){const safe=section.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");if(!new RegExp(`^#{1,6}\\s+${safe}\\s*$`,"im").test(skill.body))push(findings,{id:`quality.section.${section.toLowerCase()}`,severity:"warning",title:`Missing '${section}' section`,message:`Add a ${section} heading so reviewers can understand the skill contract.`,category:"quality"})}if(skill.body.trim().length<120)push(findings,{id:"quality.body-too-short",severity:"warning",title:"Skill instructions are too short",message:"Provide enough detail for deterministic execution and review.",category:"quality"});return permissions}
function patternScan(skill,permissions,findings){const declared=new Set(permissions);for(const [id,title,source,required,message] of RULES){const regex=new RegExp(source.source,source.flags);let match,count=0;while((match=regex.exec(skill.raw))&&count<5){count++;if(required&&declared.has(required))continue;push(findings,{id,title,message:required?`${message} Declare '${required}' or remove the capability.`:message,category:id.startsWith("permission")?"permission":"security",line:lineAt(skill.raw,match.index),evidence:match[0].slice(0,160),requiredPermission:required||undefined})}}}
function compare(skill,baseline,policy){const findings=[];if(!baseline)return findings;const previous=baseline.skills?.[skill.name]||Object.values(baseline.skills||{})[0];if(!previous)return findings;const drop=previous.score-skill.score;if(drop>policy.regression.maxScoreDrop)push(findings,{id:"regression.score-drop",title:"Reliability score regressed",message:`Score dropped ${drop} points from ${previous.score} to ${skill.score}.`,category:"regression"});if(policy.regression.failOnNewErrors&&skill.errors>(previous.errors||0))push(findings,{id:"regression.new-errors",title:"New blocking findings",message:`Errors increased from ${previous.errors||0} to ${skill.errors}.`,category:"regression"});const added=skill.permissions.filter(p=>!(previous.permissions||[]).includes(p));if(policy.regression.failOnPermissionExpansion&&added.length)push(findings,{id:"regression.permission-expansion",title:"Permission scope expanded",message:`New permissions: ${added.join(", ")}.`,category:"regression",evidence:added.join(", ")});return findings}
async function digest(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("")}
export async function scanSkill(raw,options={}){const policy={...POLICY,...options.policy,regression:{...POLICY.regression,...options.policy?.regression}};const parsed=parseSkill(raw),findings=[];const permissions=validate(parsed,policy,findings);patternScan(parsed,permissions,findings);const errors=findings.filter(x=>x.severity==="error").length,warnings=findings.filter(x=>x.severity==="warning").length;const score=Math.max(0,100-errors*18-warnings*6);const skill={name:String(parsed.frontmatter.name||"unnamed-skill"),description:String(parsed.frontmatter.description||""),version:String(parsed.frontmatter.version||"0.0.0"),permissions,findings,errors,warnings,score,risk:errors>=3?"critical":errors?"high":warnings>=2?"medium":"low",fingerprint:await digest(raw)};const regressionFindings=compare(skill,options.baseline,policy);const all=[...findings,...regressionFindings];const status=all.some(x=>x.severity==="error")||score<policy.minimumScore?"fail":all.length?"warn":"pass";return{generatedAt:new Date().toISOString(),status,policy,skill,regressionFindings,summary:{errors:all.filter(x=>x.severity==="error").length,warnings:all.filter(x=>x.severity==="warning").length,findings:all.length}}}
export function makeBaseline(report){return{version:1,approvedAt:new Date().toISOString(),skills:{[report.skill.name]:{score:report.skill.score,errors:report.skill.errors,warnings:report.skill.warnings,permissions:report.skill.permissions,fingerprint:report.skill.fingerprint}}}}
export function reportToMarkdown(report){const rows=[`# SkillCheck report: ${report.skill.name}`,"",`- Status: **${report.status.toUpperCase()}**`,`- Score: **${report.skill.score}/100**`,`- Version: ${report.skill.version}`,`- Risk: ${report.skill.risk}`,"","## Findings",""];const all=[...report.skill.findings,...report.regressionFindings];if(!all.length)rows.push("No findings.");else for(const f of all)rows.push(`- **${f.severity.toUpperCase()} — ${f.title}**${f.line?` (line ${f.line})`:""}: ${f.message}`);return rows.join("\n")+"\n"}
